blank_issues_enabled: false
contact_links:
  - name: Bug reports
    url: https://github.com/FakeFishGames/Barotrauma/discussions/categories/bug-reports
    about: Please post your bug reports in the Discussions section.