using Microsoft.Xna.Framework;
using System;
using System.Collections.Generic;
using System.Xml.Linq;

namespace Barotrauma
{
    class DecalPrefab : IPrefab, IHasUintIdentifier, IDisposable
    {
        public readonly string Name;

        public string OriginalName { get { return Name; } }

        public string Identifier
        {
            get;
            private set;
        }

        /// <summary>
        /// Unique identifier that's generated by hashing the prefab's string identifier. 
        /// Used to reduce the amount of bytes needed to write decal data into network messages in multiplayer.
        /// </summary>
        public uint UIntIdentifier { get; set; }

        public string FilePath { get; private set; }

        public ContentPackage ContentPackage { get; private set; }

        public void Dispose()
        {
            foreach (Sprite spr in Sprites)
            {
                spr.Remove();
            }
            Sprites.Clear();
        }

        public readonly List<Sprite> Sprites;

        public readonly Color Color;

        public readonly float LifeTime;
        public readonly float FadeOutTime;
        public readonly float FadeInTime;

        public DecalPrefab(XElement element, ContentFile file)
        {
            Name = element.Name.ToString();

            Identifier = Name.ToLowerInvariant();

            FilePath = file.Path;

            ContentPackage = file.ContentPackage;

            Sprites = new List<Sprite>();

            foreach (XElement subElement in element.Elements())
            {
                if (subElement.Name.ToString().Equals("sprite", StringComparison.OrdinalIgnoreCase))
                {
                    Sprites.Add(new Sprite(subElement));             
                }
            }

            Color = element.GetAttributeColor("color", Color.White);

            LifeTime = element.GetAttributeFloat("lifetime", 10.0f);
            FadeOutTime = Math.Min(LifeTime, element.GetAttributeFloat("fadeouttime", 1.0f));
            FadeInTime = Math.Min(LifeTime - FadeOutTime, element.GetAttributeFloat("fadeintime", 0.0f));
        }
    }
}
